spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/guidevologda}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_USERNAME:root}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8090

yandex:
  url: https://geocode-maps.yandex.ru/1.x/?
  geocoder: api-key

cloud:
  aws:
    credentials:
      secret-key: secret_key
      access-key: access_key
    region:
      static: storage.yandexcloud.net
    stack:
      auto: false

application:
  bucket:
    name: guidevologda

admin:
  username: admin
  password: admin